<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$_postCollection = $block->getPostCollection();
$number = 0;
?>
<?php if ($_postCollection->count()) { ?>
    <div class="post-list-wrapper blog-widget-recent zoo-title-style-flower">
    <div class="zoo-main-heading">
        <div class="zoo-heading-wrapper-title">
            <h3><span><?php echo $block->escapeHtml($block->getTitle()) ?></span></h3>
        </div>
    </div>
    <div class="row">
            <?php foreach ($_postCollection as $key=>$_post) { ?>
                <?php
                $_postUrl = $_post->getPostUrl();
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                $number = $number + 1;
                ?>
                <div class="col-xs-12 col-sm-6 col-md-3 post-item post-item-<?php echo $number;?>">
                    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        <div class="post-images">
                            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>"/>
                            </a>
                        </div>
                    <?php } ?>
                    <div class="post-header">

                            <div class="post-categories">
                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                <?php $n = 0;
                                foreach ($_post->getParentCategories() as $ct) {
                                    $n++; ?>
                                    <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>"
                                       href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                                    <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                                <?php } ?>
                            <?php } ?>
                            </div>
                        <div class="post-title">
                            <a class="post-item-link"
                               href="<?php echo $_postUrl ?>">
                                <?php echo $_postName; ?>
                            </a>
                        </div>
                        <div class="post-text-hld clearfix">
                            <?php echo $block->getShorContent($_post) ?>
                        </div>
                        <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>" >
                            <?php echo __('Lire la suite') ?>
                        </a>
                    </div>
                </div>
            <?php } ?>
    </div>
    </div>
<?php } ?>