<?php
/**
 * @category    CleverSoft
 * @package     CleverProduct
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author      ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<?php
$radom = $block->getRandom();
?>
<div class="swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId().$radom; ?> swatch-opt"
     data-swatch-obj-data-id="id_<?php /* @escapeNotVerified */ echo $block->getProduct()->getId().$radom; ?>" >
</div>
<script>
    if (typeof swatch_obj_data == "undefined") {
        var swatch_obj_data = {};
    }
    swatch_obj_data.id_<?php /* @escapeNotVerified */ echo $block->getProduct()->getId().$radom; ?> = {
        selectorProduct: '.product-item-cleverSwatchRenderer',
        onlySwatches: true,
        enableControlLabel: false,
        inProductList: true,
        selectorProductTile: '.zoo-inner-product-item-info',
        numberToShow: <?php /* @escapeNotVerified */ echo $block->getNumberSwatchesPerProduct(); ?>,
        jsonConfig: <?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>,
        jsonSwatchConfig: <?php /* @escapeNotVerified */ echo $block->getJsonSwatchConfig(); ?>,
        mediaCallback: '<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>'
    };

    require(["jquery", "jquery/ui", "cleverSwatchRenderer"], function ($) {
        $( ".swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId().$radom; ?>" ).each(function( index ) {
            if ($(this).find(".swatch-attribute").length == 0){var data_id = $(this).data("swatch-obj-data-id");
                var data_config = swatch_obj_data[data_id];
                $(this).cleverSwatchRenderer(data_config);
            }
        });
    });
</script>
