<div class="diagnosticpeau_resultats">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis consectetur lorem, eu vehicula magna consequat nec. Aliquam consequat eros malesuada, tempus ipsum eget, dapibus justo. Suspendisse congue ultrices felis in varius. Vestibulum pulvinar mauris risus, ut pharetra justo vestibulum pellentesque. Nulla non</p>
<h4>Ma routine beauté adaptée</h4>
<div class="row">
    <div class="col-sm-9">
        <div class="diagnosticpeau_resultat">
            <div class="text-center">
                <img src="{{media url="wysiwyg/images/icons/illustrations_routine/demaquille.png"}}" alt="" />
                <h4>1- Je démaquille</h4>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis consectetur lorem, eu vehicula magna consequat nec. <a href="#">Aliquam consequat</a> eros malesuada, tempus ipsum eget, dapibus justo. Suspendisse congue ultrices felis in varius. Vestibulum pulvinar mauris risus, ut pharetra justo vestibulum pellentesque. <strong>Nulla non felis ut massa faucibus efficitur.</strong></p>
            <p>Morbi fringilla id lectus non pellentesque. Sed mattis nulla convallis risus bibendum eleifend. Aenean eget hendrerit justo, vel aliquet velit. Sed quis urna id nisl gravida scelerisque <a href="#">gravida nec nunc</a> . Proin eu arcu interdum, ullamcorper risus at, elementum metus. Sed </p>
        </div>
        <div class="diagnosticpeau_resultat">
            <div class="text-center">
                <img src="{{media url="wysiwyg/images/icons/illustrations_routine/nettoie.png"}}" alt="" />
                <h4>2- Je nettoie</h4>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis consectetur lorem, eu vehicula magna consequat nec.

                Aliquam consequat eros malesuada, tempus ipsum eget, dapibus justo. Suspendisse congue ultrices felis in varius.

                <a href="#">Vestibulum pulvinar mauris risus</a> , ut pharetra justo vestibulum pellentesque. </p>
        </div>
        <div class="diagnosticpeau_resultat">
            <div class="text-center">
                <img src="{{media url="wysiwyg/images/icons/illustrations_routine/hydrate.png"}}" alt="" />
                <h4>3- J’hydrate</h4>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis consectetur lorem, eu vehicula magna consequat nec. <a href="#">Aliquam consequat</a> eros malesuada, tempus ipsum eget, dapibus justo. Suspendisse congue ultrices felis in varius. Vestibulum pulvinar mauris risus, ut pharetra justo vestibulum pellentesque. <strong>Nulla non felis ut massa faucibus efficitur.</strong></p>
            <p>Morbi fringilla id lectus non pellentesque. Sed mattis nulla convallis risus bibendum eleifend. Aenean eget hendrerit justo, vel aliquet velit. Sed quis urna id nisl gravida scelerisque <a href="#">gravida nec nunc</a> . Proin eu arcu interdum, ullamcorper risus at, elementum metus. Sed </p>
        </div>
        <div class="diagnosticpeau_resultat">
            <div class="text-center">
                <img src="{{media url="wysiwyg/images/icons/illustrations_routine/soins_specifiques.png"}}" alt="" />
                <h4>4- Soin spécifique</h4>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mollis consectetur lorem, eu vehicula magna consequat nec.

                Aliquam consequat eros malesuada, tempus ipsum eget, dapibus justo. Suspendisse congue ultrices felis in varius.

                <a href="#">Vestibulum pulvinar mauris risus</a> , ut pharetra justo vestibulum pellentesque. </p>
        </div>
        <div class=" d-flex justify-content-end">
            <div class="button-link"><input class="button" type="submit" value="précédent"></div>
            <div class="button-link"><input class="button" type="submit" value="j’enregistre ma routine"></div>
        </div>
    </div>
    <div class="col-sm-3">{{widget type="CleverSoft\CleverBlock\Block\Widget" classes="" enable_fullwidth="0" block_ids="18" block_lg="18,12," block_md="18,12," block_sm="18,12," block_xs="18,12," template="widget/block.phtml" }}</div>
</div>
</div>