<?php
$_matoHelper = $this->helper('CleverSoft\Base\Helper\Data');
?>
<div class="contact">
   <div class="row">
      <div class="col-xs-12">
         <div class="row">
            <div class="col-sm-6 text_column">
               <h3><?php /* @escapeNotVerified */ echo __('Let’s Talk Together') ?></h3>
               <p><?php /* @escapeNotVerified */ echo __('You already know what we do. Now all you have to do is get in touch<br> with us. Give us a call, shoot us an email, or drop in for some<br> wonderfully brewed coffee.') ?></p>
            </div>
            <div class="col-sm-6 contact-maps padding-left-60">
                <?php include ($block->getTemplateFile('Magento_Contact::map.phtml')) ?>
            </div>
         </div>
      </div>
   </div>
   <div class="row">
      <div class="col-xs-12 col-sm-6 ">
         <h3><?php /* @escapeNotVerified */ echo __('Send A Message') ?></h3>
         <form class="contact-form"
          action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
          data-mage-init='{"validation":{}}'>
           
            <p><input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/></p>
            <p><input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/></p>
            <p><input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" /></p>
            <p><textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" placeholder="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea></p>   
            <?php echo $block->getChildHtml('form.additional.info'); ?>
            <div class="form-actions">
               <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="btn-novetty btn-raised primary">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>		
            </div>
         </form>
      </div>
      <div class="col-xs-12 col-sm-6 padding-left-60 hidden-xs">
          <?php echo $_matoHelper->getCfg('contact_google_map/html_google_map'); ?>
      </div>
   </div>
</div>