<?php
/**
 * @category    CleverSoft
 * @package     CleverBase
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->helper('CleverSoft\Base\Helper\Cssgen')->getDesignFile();?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->helper('CleverSoft\Base\Helper\Cssgen')->getLayoutFile();?>" />


