<?php
/**
 * @category    CleverSoft
 * @package     CleverBrands
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */

/** 
@var $block \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content 
*/
?>
<?php
$_filebrowserSetup = json_decode($block->getFilebrowserSetupObject());
$_filebrowserSetup->onInsertUrl = $this->getUrl('cleverbrand/wysiwyg_images/onInsert');
?>
<div data-mage-init='{"CleverSoft_CleverBrands/js/browser": <?php echo $block->escapeHtml(json_encode($_filebrowserSetup)); ?>}'>
    <div class="side-col"><?php echo $block->getChildHtml('wysiwyg_images.tree') ?></div>
    <div class="main-col">
        <div class="insert-title" id="content_header">
            <div class="insert-title-inner">
                <div class="insert-actions">
                    <?php echo $block->getButtonsHtml() ?>
                </div>
                <div class="title"><?php /* @escapeNotVerified */ echo $block->getHeaderText() ?></div>
            </div>
        </div>
        <div id="contents-uploader" class="contents-uploader"><?php echo $block->getChildHtml('wysiwyg_images.uploader') ?></div>
        <div id="contents"></div>
    </div>
</div>
