<?php
/**
 * @category    CleverSoft
 * @package     CleverBlock
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php

$element = $block->getElement();
$note = $element->getNote() ? '<div class="note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>
<div<?php /* @escapeNotVerified */ echo $fieldAttributes ?>>
    <?php echo $element->getLabelHtml() ?>
    <div class="admin__field-control control">
        <input style="width: 50%;" type="text" onclick="<?php echo $element->getData('onclick')?>" class="input-text admin__control-text element-value-changer input-text entities <?php if ($this->getElement()->getRequired()):?>required-entry<?php endif ?>" name="<?php echo $element->getName()?>"  id="<?php echo $element->getHtmlId()?>" value="<?php echo $element->getValue()?>">
        <?php echo $block->getChildHtml('getBtn') ?>
        <table cellspacing="0" class="data border" id="<?php echo $element->getHtmlId() ?>" style="width: 285px">
            <colgroup>
                <col width="200"/>
                <col width="1"/>
                <col width="1"/>
            </colgroup>
            <thead>
            <tr class="headings">
                <th><?php echo __('Image Url') ?></th>
                <th><?php echo __('Browse') ?></th>
                <th><?php echo __('Delete') ?></th>
            </tr>
            </thead>
            <tbody id="<?php echo $element->getHtmlId() ?>_container"></tbody>
            <tfoot>
            <td colspan="3" class="a-right"><?php echo $block->getChildHtml('addBtn') ?></td>
            </tfoot>
        </table>
    </div>
</div>
<script>
    require([
        "browser",
        "prototype"
    ],function(MediabrowserUtility) {
        var rowTemplate = '<tr id="kbRow_{{id}}">'+
            '<td><input type="text" class="input-text" name="<?php echo $element->getName() ?>[]" style="width:98%;" id="kbImage_{{id}}" value="{{value}}"/></td>'+
            '<td class="a-center"><button class="button" type="button" onclick="MediabrowserUtility.openDialog(\'<?php $block->getUrl('adminhtml/cms_wysiwyg_images/index') ?>static_urls_allowed/1/target_element_id/kbImage_{{id}}\')"><span><?php echo __('Select') ?></span></button></td>'+
            '<td class="a-center"><?php echo $block->getChildHtml('delBtn') ?></td>'+
            '</tr>';

        window.kenburnsImages = {
            baseUrl: '<?php echo $block->getStoreManager()->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA); ?>',
            template: new Template(rowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
            itemsCount: 0,
            container: $('<?php echo $element->getHtmlId() ?>_container'),
            add: function(image){
                var data = {
                    value: image || '',
                    id: ++this.itemsCount
                };
                this.container.insert({bottom: this.template.evaluate(data)});
            },
            remove: function(id){
                var tr = this.container.down('tr#kbRow_' + id);
                if (tr) tr.remove();
            }
        };

        <?php foreach ($this->getImages() as $item): ?>
        window.kenburnsImages.add('<?php echo $item ?>');
        <?php endforeach ?>
    });
</script>