<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="block related">
        <div class="block-title title">
            <h3 id="block-relatedposts-heading" class="text-center" role="heading" aria-level="2">
                <?php echo __('You Might Also Like') ?>
            </h3>
        </div>
        <div class="block-content row">
            <?php foreach ($_postCollection as $_post) { ?>

                <?php
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                ?>
                <div class="item col-xs-4">
                    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        <div class="item-img">
                            <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                        </div>
                    <?php } ?>
                    <div class="item-info">
                        <p class="item-publishdate">
                            <?php echo $_post->getPublishDate('F d, Y') ?>
                        </p>
                        <h5>
                            <a class="post-item-link"
                               href="<?php echo $_post->getPostUrl() ?>">
                                <?php echo $block->escapeHtml($_post->getTitle()) ?>
                            </a>
                        </h5>
                    </div>
                </div>

            <?php } ?>
        </div>
    </div>
    <?php } ?>
<?php } ?>