<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 * 
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($_description = $block->getCurrentCategory()->getDescription()): ?>
    <div class="category-description">
        <h1><?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?></h1>
    </div>
<?php endif; ?>
