<?php
/**
 * @category    CleverSoft
 * @package     CleverLayeredNavigation
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="transparent-bg"></div>
    <div id="zoo-layer-navigation">
        <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
            <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
            <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
                <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
            </div>
            <div class="block-content filter-content">
                <?php echo $block->getChildHtml('state') ?>

                <?php if ($block->getLayer()->getState()->getFilters()): ?>
                    <div class="block-actions filter-actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                    </div>
                <?php endif; ?>
                <?php $wrapOptions = false; ?>
                <?php $number = 0; ?>
                <?php foreach ($block->getFilters() as $filter):?>
                    <?php if ($filter->getItemsCount()): ?>
                        <?php $number++; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php foreach ($block->getFilters() as $filter): ?>
            <?php if ($filter->getItemsCount()): ?>
            <?php if (!$wrapOptions): ?>
                <h4 role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></h4>
                <div class="filter-options" id="narrow-by-list" data-role="content">
                    <?php  $wrapOptions = true; endif; ?>
                    <div data-role="collapsible" class="zoo-filter-options-item filter-options-item">
                        <div data-role="title" class="zoo-filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                        <div data-role="content" class="zoo-filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                    </div>
                    <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="loading-bar"></div>
<?php endif; ?>