<?php
/**
 * @category    CleverSoft
 * @package     CleverDeferJs
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<script>
    require(['jquery'],function($){
        $(function(){
            $('body','html').find('iframe').each(function(){
                var $iframe = $(this);
                var $src = $iframe.attr('src');
                $iframe.attr('src','');
                $iframe.attr('data-src',$src);
            });
        })
        window.onload = function(){
            $('body','html').find('iframe').each(function(){
                $(this).attr('src', $(this).attr('data-src'));
            });
        }
    })
</script>