<?php
/**
 * @category    CleverSoft
 * @package     CleverBase
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */

$blockFooter = $this->getBlocks();
?>
<div class="footer container">
	<div class="row">
    <?php foreach ($blockFooter as $block): ?>
        <div class="<?php echo $block['class'] ?>">
            <?php echo $block['content'] ?>
        </div>
    <?php endforeach ?>
	</div>
</div>
