<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <div class="custom-qty">
                    <button type="button"  class="increase items items-count" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;">
                        +
                    </button>
                    <button type="button" class="reduced items  items-count" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) && qty > 1 ) result.value--;return false;">
                        -
                    </button>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit" 
                    class="action tocart btn-novetty"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            $('.product_addtocart_form_<?php echo($_product->getId())?>').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });
                    widget.catalogAddToCart('submitForm', $(form));
                    $('.block.block-minicart').dropdownDialog('open');
//                $('.header-content .action.showcart').addClass('active');
//                $('.header-content .ui-dialog.ui-widget.ui-widget-content.ui-corner-all.ui-front.mage-dropdown-dialog').show();
                    return false;
                },
                errorPlacement: function (error, element) {
                    var errorPlacement = element;
                    // logic for date-picker error placement
                    if (element.hasClass('hasDatepicker')) {
                        errorPlacement = element.siblings('img');
                    }
                    // logic for field wrapper
                    var fieldWrapper = element.closest('.addon');
                    if (fieldWrapper.length) {
                        errorPlacement = fieldWrapper.after(error);
                    }
                    //logic for checkboxes/radio
                    if (element.is(':checkbox') || element.is(':radio')) {
                        errorPlacement = element.siblings('label').last();
                    }
                    var $top = $(window).scrollTop();
                    var $target = errorPlacement.offset().top;
                    errorPlacement.after(error);
                    if($top > $target) {
                        $("html, body").animate({ scrollTop: $target-200 }, 600);
                    }
                    $('.block.block-minicart').dropdownDialog('close');
//                $('.action.showcart').removeClass('active');
//                $('.ui-dialog.ui-widget.ui-widget-content.ui-corner-all.ui-front.mage-dropdown-dialog').hide();
                }
            });
        });
    </script>
<?php endif; ?>