<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$_settingHelper = $this->helper('CleverSoft\Base\Helper\Data');
$_product = $block->getProduct();
if($_product->getIsSalable()) $product_stock = 'product-instock'; else $product_stock = 'product-oustock';

?>


<?php if ($_product->getIsSalable()): echo '<div class="label-product-view">'.$_settingHelper->getLabel($block->getProduct()).'</div>'; ?>
<?php else : ?>
    <div class="stock unavailable"><span><?php /* @escapeNotVerified */  echo __('Out of stock') ?></span></div>
<?php endif; ?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <div class="zoo-clazyload-spinners qw"></div>
        </div>
    </div>

</div>

<?php
$theme = $this->helper('CleverSoft\Base\Helper\Data');
$product_layout  = $theme->getCfg('product_page/page_layout');
/* Image size */
if(!($main_width = $_settingHelper->getCfg('product_page/main_image_width')))
    $main_width = $block->getImageAttribute('product_page_image_medium', 'width');
if(!($main_height = $_settingHelper->getCfg('product_page/main_image_height')))
    $main_height = $block->getImageAttribute('product_page_image_medium', 'height');
if(!($thumb_width = $_settingHelper->getCfg('product_page/thumb_image_width')))
    $thumb_width = $block->getImageAttribute('product_page_image_small', 'width');
if(!($thumb_height = $_settingHelper->getCfg('product_page/thumb_image_height')))
    $thumb_height = $block->getImageAttribute('product_page_image_small', 'height');

switch ($product_layout) {
    case 'horizontal_thumb':
        $gallerylayout = 'horizontal';
        break;
    case 'center_vertical_thumb':
        $gallerylayout = 'vertical';
        break;
    case 'vertical_thumb':
        $gallerylayout = 'vertical';
        break;
    default:
        $gallerylayout = $block->getVar('gallery/navdir');
}
?>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?php /* @escapeNotVerified */ echo $block->getMagnifier(); ?>,
                "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson(); ?>,
                "options": {
                    "nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/nav"); ?>",
                    "loop": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/loop"); ?>,
                    "keyboard": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/keyboard"); ?>,
                    "arrows": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/arrows"); ?>,
                    "allowfullscreen": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/allowfullscreen"); ?>,
                    "showCaption": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/caption"); ?>,
                    "width": <?php /* @escapeNotVerified */ echo $main_width; ?>,
                    "thumbwidth": <?php /* @escapeNotVerified */ echo $thumb_width; ?>,
                    "thumbheight": <?php /* @escapeNotVerified */ echo $thumb_height ?: $thumb_width; ?>,
                    "height": <?php /* @escapeNotVerified */ echo $main_height ?: $main_width; ?>,
                    "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/duration"); ?>,
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/effect"); ?>",
                    "navarrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/navarrows"); ?>,
                    "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
                    "navdir": "<?php /* @escapeNotVerified */  echo $gallerylayout; ?>"
                },
                "fullscreen": {
                    "nav": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/nav"); ?>",
                    "loop": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/loop"); ?>,
                    "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navdir"); ?>",
                    "arrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/arrows"); ?>,
                    "showCaption": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/caption"); ?>,
                    "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
                },
                "breakpoints": <?php /* @escapeNotVerified */ echo $block->getBreakpoints(); ?>
            }
        }
    }
</script>