<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post = $this->getPost();
$imageWidth = $block->getConfigImage('mfblog/post_list/image_width') ? $block->getConfigImage('mfblog/post_list/image_width') : 500;
$imageHeight = $block->getConfigImage('mfblog/post_list/image_height') ? $block->getConfigImage('mfblog/post_list/image_height') : 300;
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);
$index = $this->getIndex();
?>
<div class="col-sm-12 post-item <?php echo ($index == 1 ? 'col-md-12': 'col-md-4'); ?> post-item-<?php echo $index;?>">

        <?php if ($featuredImage = $_post->getData('featured_img')) { ?>
            <div class="post-images">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <img src="<?php echo $this->helper('Magefan\Blog\Helper\Image')->init($featuredImage)->resize($imageWidth, $imageHeight); ?>" alt="<?php echo $_postName ?>" />
                </a>
            </div>
        <?php } ?>

    <div class="post-header">

        <div class="post-categories">
            <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                <?php $n = 0;
                foreach ($_post->getParentCategories() as $ct) {
                    $n++; ?>
                    <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>"
                       href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                    <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                <?php } ?>
            <?php } ?>
        </div>

        <div class="post-title">
            <a class="post-item-link"
               href="<?php echo $_postUrl ?>">
                <?php echo $_postName; ?>
            </a>
        </div>

        <div class="post-text-hld clearfix">
            <?php echo $block->getShorContent($_post) ?>
        </div>
        <a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>" >
            <?php echo __('Lire la suite') ?>
        </a>
    </div>
</div>