<?php
/**
 * @category    CleverSoft
 * @package     CleverBlock
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php

$element = $block->getElement();
$note = $element->getNote() ? '<div class="note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
$ranId = $block->getRandom()->getUniqueHash('categories');
?>
<div<?php /* @escapeNotVerified */ echo $fieldAttributes ?>>
    <?php echo $element->getLabelHtml() ?>
    <div class="admin__field-control control">
        <input style="width: 25%;" type="text" class="input-text admin__control-text element-value-changer input-text entities <?php if ($this->getElement()->getRequired()):?>required-entry<?php endif ?>" name="<?php echo $element->getName()?>" readonly id="<?php echo $element->getHtmlId()?>" value="<?php echo $element->getValue()?>">
        <label class="addafter"><a class="rule-chooser-trigger" href="javascript:void(0)" onclick="mtWidgetProduct.displayEntityChooser('<?php echo $ranId ?>')" title="<?php echo __('Open Chooser')?>">
            <img class=rule-chooser-trigger" src="<?php echo $block->getViewFileUrl('CleverSoft_CleverBlock::images/rule_chooser_trigger.gif')?>"/>
        </a></label>
        <a class="rule-param-apply" href="javascript:void(0)" onclick="mtWidgetProduct.hideEntityChooser('<?php echo $ranId ?>')" title="<?php echo __('Apply')?>">
            <img class="v-middle" src="<?php echo $block->getViewFileUrl('CleverSoft_CleverBlock::images/rule_component_apply.gif')?>"/>
        </a>
        <a class="rule-param-remove" href="javascript:void(0)" onclick="mtWidgetProduct.clearEntityValue('<?php echo $ranId ?>')" title="<?php echo __('Clear value')?>">
            <img class="v-middle" src="<?php echo $block->getViewFileUrl('CleverSoft_CleverBlock::images/rule_component_remove.gif')?>"/>
        </a>
        <div id="<?php echo $ranId?>" class="grid-container"></div>
    </div>
</div>

<script>
    require([
        "CleverSoft_CleverBlock/js/widget",
        "prototype"
    ],function(MTWidgetChooser) {
        window.mtWidgetProduct = new MTWidgetChooser('<?php echo $block->getProductsChooserUrl()?>');
        
        jQuery(function(){
            Event.observe(document, 'productNode:changed', function(event){
                window.mtWidgetProduct.checkProduct(event);
            });
        });

    });
</script>
