<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="header-compare item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <i class="cs-font clever-icon-compare-6"></i>
    <a class="action compare" title="<?php /* @escapeNotVerified */ echo __('Compare Products') ?>"
       data-bind="attr: {'href': compareProducts().listUrl}"
    >
        <span class="counter-number counter qty" data-bind="text: compareProducts().countCaption"></span>
    </a>
</div>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>
