<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct()
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper">
        <div class="data table additional-attributes" id="product-attribute-specs-table">
            <?php foreach ($_additional as $_data): ?>
                <?php if($_data['code'] == 'conditionnement'): ;?>
                <div class="attribute-conditionnement attribute-custom">
                    <div><label><?php echo $block->escapeHtml(__($_data['label'])) ?>:</label></div>
                    <p><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></p>
                </div>
            <?php endif;?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;?>
