<?php
/**
 * @category    CleverSoft
 * @package     CleverSlider
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php
use \Magento\Framework\App\ObjectManager;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection');
$menus = $connection->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION')->fetchAll("SELECT * FROM ".$connection->getTableName('clever_slideshow'));

?>
<div class="slider-container" id="editting-tabs">
    <ul >
        <li>
            <a href="#slider-form-outer"><?php echo __('General Settings') ?></a>
        </li>
        <li>
            <a href="#tabs-main-editing"><?php echo __('Edit Slider') ?></a>
        </li>
    </ul>
    <div class="top-container" id="slider-form-outer">
		<div class="slider-form-inner" id="slider-form-inner" >
			<?php echo $this->getChildHtml('slideshow_newaction') ?>
		</div>
    </div>
    <div class="bottom-container" id="tabs-main-editing">
        <?php if(count($menus) > 1): ?>

            <div class="selections-container">
                <div class="manage-menus">
                    <label for="slider-selection-submit"><?php echo __('Select a slideshow to edit:') ?></label>
                    <select id="slider-selection-submit" onchange="window.location = this.value">
                        <?php $id = $block->getRequest()->getParam('id'); ?>
                        <?php if(is_null($id)) {
                            echo '<option selected>'.__('Select Slider').'</option>';
                        } ?>
                        <?php foreach ($menus as $menu) : ?>
                            <option <?php echo $id == $menu['id'] ? 'selected' : ''; ?> value="<?php echo $block->getUrl('slideshow/index/new',['id' => $menu['id']]) ?>"><?php echo $menu['title']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <span>Or <a class="blue" href="<?php echo $block->getUrl('slideshow/index/new'); ?>"><?php echo __('create a new slideshow'); ?></a></span>
                </div>
            </div>


        <?php else : ?>
            <div class="selections-container">
                <div class="manage-menus">
                    <span class="add-edit-slider-action"><?php echo __('Edit your slideshow below, or'); ?> <a class="blue" href="<?php echo $block->getUrl('slideshow/index/new'); ?>"><?php echo __('create a new slideshow'); ?></a>.		</span>
                </div>
            </div>
        <?php endif ?>
		<?php echo $this->getChildHtml('slider_item_types') ?>
        <?php echo $this->getChildHtml('slider_items_layout') ?>
        <?php echo $this->getChildHtml('slider_items_icons_panel') ?>
        <?php echo $this->getChildHtml('slider_col_templates_panel') ?>
    </div>
</div>
