<?php
/**
 * @category    CleverSoft
 * @package     CleverBlock
 * @copyright   Copyright © 2017 CleverSoft., JSC. All Rights Reserved.
 * @author 		ZooExtension.com
 * @email       magento.cleversoft@gmail.com
 */
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<?php
$radom = $block->getRandom();
?>
<div class="swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId().$radom ?>"
     data-mage-init='{"cleverSwatchRenderer":{
                    "selectorProduct":".product-item-details",
                    "onlySwatches":"true",
                    "enableControlLabel":"false",
                    "numberToShow":"<?php /* @escapeNotVerified */ echo $block->getNumberSwatchesPerProduct(); ?>",
                    "jsonConfig":<?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>,
                    "jsonSwatchConfig":<?php /* @escapeNotVerified */ echo $block->getJsonSwatchConfig(); ?>,
                    "mediaCallback":"<?php /* @escapeNotVerified */ echo $block->getMediaCallback(); ?>"
                }}'
></div>
